language: python
python:
  - "3.4"
install: "pip install -r requirements.txt -r requirements-dev.txt"
before_script: python setup.py develop
script: mamba
after_success: coverage run --source="./pysellus" ~/virtualenv/python3.4/bin/mamba && coveralls
